export const FAKE_POPULARS = [
  {
    backdrop_path: "/iDUgitOS7GA1rRZCRL0JsCdyREf.jpg",
    first_air_date: "2022-05-27",
    genre_ids: [18, 10751],
    id: 203057,
    name: "Melur Untuk Firdaus",
    origin_country: ["MY"],
    original_language: "ms",
    original_name: "Melur Untuk Firdaus",
    overview:
      "Melur Untuk Firdaus is a 2022 Malaysian television drama series directed by Zamri Zakaria with a script by Wan Mahani Wan Hasan. Starring Anna Jobling, Meerqeen, Nesa Idrus, Fimie Don and many others, this series is an adaptation of the novel My Rude Wife by Cik Nor Cinta and started airing on Slot Lestary, TV3 from 27 May 2022 until 15 July 2022 replacing Do You Love Me Captain.",
    popularity: 2064.534,
    poster_path: "/rVxQxsY3bQWTabHUi2Qr3aoOafk.jpg",
    vote_average: 3.8,
    vote_count: 4,
  },
];

export const FAKE_RECOMMENDATIONS = [
  [
    {
      adult: false,
      backdrop_path: "/lpLDBRl4K2xW6WPVR0TjhqQ1LSD.jpg",
      id: 133727,
      name: "Acapulco",
      original_language: "en",
      original_name: "Acapulco",
      overview:
        "Twenty-something Máximo Gallardo's dreams comes true when he gets the job of a lifetime as a cabana boy at the hottest resort in Acapulco. He soon realizes the job is far more complicated than he ever imagined and in order to succeed, he must learn to navigate a demanding clientele, a mercurial mentor, and a complicated home life, without losing his way to shortcuts or temptations.",
      poster_path: "/gzBkO4zFr75A13GKnjvTeg25pze.jpg",
      media_type: "tv",
      genre_ids: [35],
      popularity: 59.045,
      first_air_date: "2021-10-08",
      vote_average: 7.312,
      vote_count: 292,
      origin_country: ["MX"],
    },
    {
      adult: false,
      backdrop_path: "/gB9l7epUG4lZKe68bTdL6u6eZCK.jpg",
      id: 119988,
      name: "The Innocent",
      original_language: "es",
      original_name: "El inocente",
      overview:
        "An accidental killing leads a man down a dark hole of intrigue and murder. Just as he finds love and freedom, one phone call brings back the nightmare.",
      poster_path: "/pfGlHuTMglPfgKJ84LmMvBAJdhr.jpg",
      media_type: "tv",
      genre_ids: [80, 9648, 18],
      popularity: 14.356,
      first_air_date: "2021-04-30",
      vote_average: 7.7,
      vote_count: 269,
      origin_country: ["ES"],
    },
    {
      adult: false,
      backdrop_path: "/v6gog3v6BjTrXhsaVfTCDHurFLe.jpg",
      id: 103086,
      name: "All For Love",
      original_language: "es",
      original_name: "Amar y Vivir",
      overview:
        "A penniless country boy goes in search of his runaway sister in Bogotá, where he falls for an aspiring singer, but gets tangled up in organized crime.",
      poster_path: "/jjmLFjKKnxyRq07lyD29wPbRM2d.jpg",
      media_type: "tv",
      genre_ids: [],
      popularity: 26.862,
      first_air_date: "2020-01-07",
      vote_average: 7.437,
      vote_count: 334,
      origin_country: ["CO"],
    },
    {
      adult: false,
      backdrop_path: "/wftQqLZ1QfoUkodR9TxFlch2ji3.jpg",
      id: 105213,
      name: "Kissing Game",
      original_language: "pt",
      original_name: "Boca a Boca",
      overview:
        'At a high school in a rural, isolated ranching community, families panic when teens contract a mysterious "kissing disease" that quickly spreads.',
      poster_path: "/i0Gmbo25STtJBIxTFyQpqw7Thxl.jpg",
      media_type: "tv",
      genre_ids: [18, 9648],
      popularity: 13.878,
      first_air_date: "2020-07-17",
      vote_average: 7.032,
      vote_count: 253,
      origin_country: ["BR"],
    },
    {
      adult: false,
      backdrop_path: "/gq27Ul37NvBuFLT9qIzquT9NL8V.jpg",
      id: 61915,
      name: "K.C. Undercover",
      original_language: "en",
      original_name: "K.C. Undercover",
      overview:
        "K.C. Cooper, a high school math whiz and karate black-belt, learns that her parents are spies when they recruit her to join them in the secret government agency, The Organization. While she now has the latest spy gadgets at her disposal, K.C. has a lot to learn about being a spy, including keeping her new gig a secret from her best friend Marisa. Together, K.C. and her parents, Craig and Kira, and her younger siblings, Ernie and Judy (a humanoid robot), try to balance everyday family life while on undercover missions, near and far, to save the world.",
      poster_path: "/52iv1yPKYR4nezoX7lMLcK9yt6q.jpg",
      media_type: "tv",
      genre_ids: [10762, 35, 10751, 18],
      popularity: 38.54,
      first_air_date: "2015-01-18",
      vote_average: 8,
      vote_count: 143,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/tcF46ItZ4aVsUlkTal5ZKeYukNj.jpg",
      id: 213241,
      name: "Lockwood & Co.",
      original_language: "en",
      original_name: "Lockwood & Co.",
      overview:
        "A girl with extraordinary psychic abilities joins two gifted teen boys at a small ghost-hunting agency to fight the many deadly spirits haunting London.",
      poster_path: "/lxWSGo8D6MbFbQmM9tqhbaG80TP.jpg",
      media_type: "tv",
      genre_ids: [10765],
      popularity: 29.311,
      first_air_date: "2023-01-27",
      vote_average: 7.919,
      vote_count: 111,
      origin_country: ["GB"],
    },
    {
      adult: false,
      backdrop_path: "/3IPmnpvYHWspBbSG4ERp45yWdQ4.jpg",
      id: 126526,
      name: "Elite Short Stories: Nadia Guzmán",
      original_language: "es",
      original_name: "Elite Histórias Breves: Nadia Guzmán",
      overview:
        "Nadia feels conflicted about whether or not to see her long distance boyfriend, Guzmán, when she returns to Spain for her sister's wedding.",
      poster_path: "/txUNc9yruQ0I6JFL5vHtWO8WBNQ.jpg",
      media_type: "tv",
      genre_ids: [18],
      popularity: 12.817,
      first_air_date: "2021-06-15",
      vote_average: 7.418,
      vote_count: 170,
      origin_country: ["ES"],
    },
    {
      adult: false,
      backdrop_path: "/umzY0SKuCP8vZNK2wjZfgfFfy8Y.jpg",
      id: 40244,
      name: "The Client List",
      original_language: "en",
      original_name: "The Client List",
      overview:
        "Riley Parks delicately balances two starkly different lives -- one as a single mom in a conservative town struggling to provide for her family and the other as a savvy and ambitious businesswoman working with a rowdy, sexy and unpredictable group of women.",
      poster_path: "/14T9c7aBwYlsqAc3ShzHBJwD44T.jpg",
      media_type: "tv",
      genre_ids: [18],
      popularity: 25.199,
      first_air_date: "2012-04-08",
      vote_average: 6.591,
      vote_count: 88,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/pNCZbQ5jvCbgoBfeoSx0l5dJhIM.jpg",
      id: 135864,
      name: "Elves",
      original_language: "da",
      original_name: "Nisser",
      overview:
        "The Christmas vacation of a teenage girl and her family turns into a nightmare when they discover the ancient threat that haunts the island where they are.",
      poster_path: "/6upMMT2Uz4bhJabBCWhYKESIbF4.jpg",
      media_type: "tv",
      genre_ids: [18, 9648, 10765],
      popularity: 32.997,
      first_air_date: "2021-11-28",
      vote_average: 6.956,
      vote_count: 192,
      origin_country: ["DK"],
    },
    {
      adult: false,
      backdrop_path: "/rdLfM9xPiY6CbzMCm2K4MS2zSBq.jpg",
      id: 154117,
      name: "Cecilia",
      original_language: "es",
      original_name: "Cecilia",
      overview:
        "The story of a woman whose world seemingly crumbles when she suffers a stroke. What at first seems like a tragedy ends up being an opportunity to reunite her family and rebuild her life.",
      poster_path: "/yGWTHlzIBlPGFaKHWKnrhv6Woqq.jpg",
      media_type: "tv",
      genre_ids: [18, 35],
      popularity: 5.916,
      first_air_date: "2021-12-21",
      vote_average: 7.628,
      vote_count: 78,
      origin_country: ["MX"],
    },
  ],
];
